### ISSUE TITLE
No notification showed if app is open

### ISSUE THREAD

**Issue by vishal-techbitsolution** [CatalystCode/react-native-azurenotificationhub#141] opened 2020-04-27 10:20 UTC
## Report

- [x] I have searched [existing issues](https://github.com/CatalystCode/react-native-azurenotificationhub/issues) and this is not a duplicate.

## Environment

- Platforms: Android/IOS

- Android version: 10

- iOS version: 13

## Issues and Steps to Reproduce
Send notification to app, if app is open no notification will show on device, if app is minimized/closed and try to send the notification. Device show notifications. I tried to log the notification. Notification gets logged for both cases.

## Expected Behavior
Notification should show in device even app is open.

## Actual Behavior
No notifications shows if app is open and is in foreground. Although logging shows notification received

**Comment by guptahardik17** [comment] 2020-04-28 12:37
Same issue with me also, urgently need the solution of this for iOS. 

For android, if the app is open,  then i am pushed it as local notification using react-native-notifications. This is i think not the good way even, but temporarily it works.

For iOS, i don't know how to handle it. Need your help @phongcao

**Comment by phongcao** [comment] 2020-04-28 15:38
@vishal-techbitsolution @guptahardik17 Can you try v0.9.4 and let me know if that is the expected behavior for you? In v0.9.5, iOS uses a newer notification API and by design, the system silences notifications for foreground apps:

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SchedulingandHandlingLocalNotifications.html

> **Handling Notifications When Your App Is in the Foreground**
> If a notification arrives while your app is in the foreground, you can silence that notification or tell the system to continue to display the notification interface. The system silences notifications for foreground apps by default, delivering the notification’s data directly to your app. You can use the notification data to update your app’s interface directly. For example, if a new sports score arrived, you would just update that information in your interface.

If you want the system to continue to display the notification interface, provide a delegate object for the `UNUserNotificationCenter` and implement the `userNotificationCenter:willPresentNotification:withCompletionHandler:` method.

**Comment by vishal-techbitsolution** [comment] 2020-04-29 05:26
Hey @phongcao I tried version 0.9.4 on android, but notifications are still not showing if app is in foreground state. It only worked if app is closed or background state.

**Comment by phongcao** [comment] 2020-04-29 14:32
@vishal-techbitsolution I'm afraid that is the expected behavior. We prefer to handle remote notifications in our app when it's in foreground rather than using alarm service to notify. What you probably want is the revert of this PR:

https://github.com/CatalystCode/react-native-azurenotificationhub/pull/109

**Comment by vishal-techbitsolution** [comment] 2020-04-29 15:13
Hey @phongcao You are correct, although I am not using react-native-firebase. But I believe I can modify FirebaseMessageService file in this packgae to test the behaviour that I expect.
```
// if (notificationHubUtil.getAppIsForeground()) {
        //     bundle.putBoolean(KEY_REMOTE_NOTIFICATION_FOREGROUND, true);
        //     bundle.putBoolean(KEY_REMOTE_NOTIFICATION_USER_INTERACTION, false);
        //     bundle.putBoolean(KEY_REMOTE_NOTIFICATION_COLDSTART, false);
        // } else {
        //     ReactNativeNotificationsHandler.sendNotification(this, bundle, notificationChannelID);
        // }

        ReactNativeNotificationsHandler.sendNotification(this, bundle, notificationChannelID);
```

**Comment by vishal-techbitsolution** [comment] 2020-04-29 15:28
Hey @phongcao I tested the android functionality with my previous message. Now, even app is in foreground state notifications are shown in notification tray.
Just wanted to know, what is the use of putboolean in functionality which I commented. I am not sure about this but if you allow I want to make a new PR with this change.

![image](https://user-images.githubusercontent.com/59605655/80614309-ea8d3080-8a5b-11ea-9f3a-7666d74d542e.png)

**Comment by phongcao** [comment] 2020-04-29 17:12
The boolean values are part of the notification payload that tell you:

- KEY_REMOTE_NOTIFICATION_FOREGROUND: true if the app is running in foreground, false otherwise.
- KEY_REMOTE_NOTIFICATION_USER_INTERACTION: true if user has tapped on the notification in the notification center, false otherwise.
- KEY_REMOTE_NOTIFICATION_COLDSTART: true if the app wasn't running and user has just launched it, false otherwise.

I don't want to change the current behavior since it's probably what other folks want and it's also consistent with react-native-firebase and iOS's implementation.

**Comment by vishal-techbitsolution** [comment] 2020-04-29 17:29
But Can't we just pass payload with sendNotification function. I believe it won't affect others functionality like this
if (notificationHubUtil.getAppIsForeground()) {
            bundle.putBoolean(KEY_REMOTE_NOTIFICATION_FOREGROUND, true);
            bundle.putBoolean(KEY_REMOTE_NOTIFICATION_USER_INTERACTION, false);
            bundle.putBoolean(KEY_REMOTE_NOTIFICATION_COLDSTART, false);
}
ReactNativeNotificationsHandler.sendNotification(this, bundle, notificationChannelID);

**Comment by vishal-techbitsolution** [comment] 2020-04-29 17:46
Also can you please confirm when are the changes of master will be released ? 
I believe it will be a part of new release and they won't be available in version 0.9.5

**Comment by phongcao** [comment] 2020-04-29 19:10
> @phongcao But Can't we just pass payload with sendNotification function. I believe it won't affect others functionality like this
> if (notificationHubUtil.getAppIsForeground()) {
> bundle.putBoolean(KEY_REMOTE_NOTIFICATION_FOREGROUND, true);
> bundle.putBoolean(KEY_REMOTE_NOTIFICATION_USER_INTERACTION, false);
> bundle.putBoolean(KEY_REMOTE_NOTIFICATION_COLDSTART, false);
> }
> ReactNativeNotificationsHandler.sendNotification(this, bundle, notificationChannelID);

No, we can't since that's the purpose of PR #109 to make the notification not shown in the center when the app is in foreground. `ReactNativeNotificationsHandler.sendNotification(...)` uses the alarm service to create the system notification.

> Also can you please confirm when are the changes of master will be released ?
> I believe it will be a part of new release and they won't be available in version 0.9.5

Yes, these changes will be integrated in the next release. I can also create a minor release for v0.9.5 later this week if that's something required for you.

**Comment by vishal-techbitsolution** [comment] 2020-04-30 03:53
@phongcao That would be great, if your can create a minor release. It will solve my pipeline issue

**Comment by vishal-techbitsolution** [comment] 2020-05-02 14:29
@phongcao can you make a release tomorrow, I am still stuck with issue. Once you make a new release I believe this will sort out everything

**Comment by phongcao** [comment] 2020-05-03 01:10
@vishal-techbitsolution  [v0.9.5-Patched.1](https://www.npmjs.com/package/react-native-azurenotificationhub/v/0.9.5-Patched.1) has been published!

**Closed** 2020-05-03 01:11 UTC

**Comment by sw-tt-keyurprajapati** [comment] 2020-08-14 10:11
How can show a notification popup on top of device when app in foreground in android?
